version: "3.8"

services:

  auth-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    expose:
      - "5431"

  auth-app:
    build: ./auth
    volumes:
      - ./auth/:/usr/src/auth/
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      - auth-db

volumes:
  postgres_data: