version: "3.8"

services:

  auth-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgre/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    env_file:
      - .env.db
    expose:
      - "5431"

  auth-app:
    build: ./auth
    volumes:
      - ./auth/:/usr/src/auth/
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      - auth-db
      - auth-redis

  auth-redis:
    image: redis:7.0.0-alpine
    restart: always
    expose:
      - "6379"

volumes:
  postgres_data: