FROM python:3.10-slim-buster

RUN mkdir -p /usr/src/auth
WORKDIR /usr/src/auth

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.txt .
COPY ./dev_requirements.txt .
RUN pip install -r dev_requirements.txt

COPY ./src /src
WORKDIR /usr/src/auth/src

ENTRYPOINT flask db init
ENTRYPOINT python app/main.py
